name: matrix
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Install google test and g++-20
      run: sudo apt-get install libgtest-dev googletest googletest-tools google-mock g++-20

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: CMake release config
      run: cmake -S . -B build

    - name: CMake release build
      run: cmake --build build

    - name: CMake release test
      run: env CTEST_OUTPUT_ON_FAILURE=1 cmake --build build --target tests
    
    - name: CMake debug build
      run: cmake --build --config Debug

    - name: CMake debug test
      run: env CTEST_OUTPUT_ON_FAILURE=1 cmake --build build --target tests
