name: Matrix
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Google Test and G++
      run: sudo apt-get install -y libgtest-dev cmake g++

    - name: CMake Build (Release)
      run: |
        cmake -S . -B build/release -DCMAKE_BUILD_TYPE=Release
        cmake --build build/release
        cd build/release
        ctest --output-on-failure

    - name: CMake Build (Debug)
      run: |
        cmake -S . -B build/debug -DCMAKE_BUILD_TYPE=Debug
        cmake --build build/debug
        cd build/debug
        ctest --output-on-failure
    - name: Run program with input 
      run: cd build ./matrix 10 12 2 -170 1742 -8 -2 -9 -10 -3 5 8 2 -17 536 -2 0 -2 -3 -1 1 22 -8 -306 1608 -14 3 -5 -7 1 3 8 -4 -34 0 -2 2 1 0 1 -1 20 -2 -153 1139 -8 3 -3 -6 0 2 58 -6 -459 3283 -23 10 -8 -17 0 6 -24 -12 -51 -1675 3 2 7 10 5 -3 -38 2 493 -4154 23 1 19 23 5 -11 -2 0 17 -335 1 1 2 2 1 -1 6 -2 -68 402 -3 1 -1 -2 0 1