name: CI for CMake Project
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Google Test and G++
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtest-dev cmake g++
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp lib/*.a /usr/lib

    - name: CMake Build (Release)
      run: |
        cmake -S . -B build/release -DCMAKE_BUILD_TYPE=Release
        cmake --build build/release
        cd build/release
        ctest --output-on-failure

    - name: CMake Build (Debug)
      run: |
        cmake -S . -B build/debug -DCMAKE_BUILD_TYPE=Debug
        cmake --build build/debug
        cd build/debug
        ctest --output-on-failure