name: CI for CMake Project
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Google Test and G++
      run: sudo apt-get install libgtest-dev googletest googletest-tools google-mock g++-20

    - name: CMake Build (Release)
      run: |
        cmake -S . -B build/release -DCMAKE_BUILD_TYPE=Release
        cmake --build build/release --target tests
        cd build/release
        ctest --output-on-failure

    - name: CMake Build (Debug)
      run: |
        cmake -S . -B build/debug -DCMAKE_BUILD_TYPE=Debug
        cmake --build build/debug --target tests
        cd build/debug
        ctest --output-on-failure